import pg from 'pg';
import { dbConfig } from '../config.js';

const pool = new pg.Pool(dbConfig);

export async function query(text, params, callback) {
	return pool.query(text, params, callback)
}

export async function createTablesIfNotExisting() {
	const puzzlesQuery = [""
		, "CREATE TABLE IF NOT EXISTS puzzles ("
		, "	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,"
		, "	guild_id VARCHAR(128) NOT NULL,"
		, "	finished BOOLEAN NOT NULL DEFAULT FALSE"
		, ");"
	].join('');

	const questionsQuery = [""
		, "CREATE TABLE IF NOT EXISTS questions ("
		, "	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,"
		, "	puzzles_id INT NOT NULL REFERENCES puzzles(id),"
		, "	question_number INT NOT NULL,"
		, "	UNIQUE(question_number, puzzles_id)"
		, ");"
	].join('');

	try {
		await query(puzzlesQuery);
		console.log('Successfully created puzzles table.');
		await query(questionsQuery);
		console.log('Successfully created questions table.');
	} catch (error) {
		console.error(`Could not create tables: ${error}`);
	}
}

