version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_HOST=db
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_DATABASE}
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - TZ=$TIMEZONE
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_DATABASE
    ports:
      - $DB_PORT:$DB_PORT
    healthcheck:
      test: pg_isready -U $DB_USER -d $DB_DATABASE
      interval: 1s
      timeout: 5s
      retries: 10
