/**
 * @type {import('node-pg-migrate').ColumnDefinitions | undefined}
 */
exports.shorthands = undefined;

/**
 * @param pgm {import('node-pg-migrate').MigrationBuilder}
 * @param run {() => void | undefined}
 * @returns {Promise<void> | void}
 */
exports.up = (pgm) => {
	pgm.sql(`
		CREATE TABLE IF NOT EXISTS answers(
			id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
			puzzle_id INT NOT NULL REFERENCES puzzles(id),
			user_id VARCHAR(127) NOT NULL,
			completed_ts TIMESTAMPTZ NOT NULL DEFAULT now(),
			UNIQUE(puzzle_id, user_id)
		);
	`);
};

/**
 * @param pgm {import('node-pg-migrate').MigrationBuilder}
 * @param run {() => void | undefined}
 * @returns {Promise<void> | void}
 */
exports.down = (pgm) => {
	pgm.dropTable('answers');
};
